-- MySQL Script generated by MySQL Workbench
-- Wed Apr  7 14:17:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 3762242_elevent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 3762242_elevent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `3762242_elevent` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `3762242_elevent` ;

-- -----------------------------------------------------
-- Table `3762242_elevent`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3762242_elevent`.`tipo` (
  `idTipo` INT NOT NULL,
  `nomeTipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3762242_elevent`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3762242_elevent`.`participante` (
  `idParticipante` INT NOT NULL,
  `nome` VARCHAR(55) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `idTipo` INT NOT NULL,
  PRIMARY KEY (`idParticipante`),
  UNIQUE INDEX `Id_UNIQUE` (`cpf` ASC),
  INDEX `fk_participante_tipo1_idx` (`idTipo` ASC),
  CONSTRAINT `fk_participante_tipo1`
    FOREIGN KEY (`idTipo`)
    REFERENCES `3762242_elevent`.`tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3762242_elevent`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3762242_elevent`.`fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tipo` INT NOT NULL,
  `telefone` VARCHAR(15) COLLATE 'utf8_unicode_ci' NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3762242_elevent`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3762242_elevent`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFim` TIME NOT NULL,
  `descricaoEvento` LONGTEXT NOT NULL,
  `situacao` CHAR(1) NOT NULL,
  `certificacao` TINYINT NOT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3762242_elevent`.`checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3762242_elevent`.`checklist` (
  `idChecklist` INT NOT NULL,
  `objeto` VARCHAR(45) NOT NULL,
  `tarefa` LONGTEXT NOT NULL,
  PRIMARY KEY (`idChecklist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3762242_elevent`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3762242_elevent`.`servico` (
  `idProduto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `evento` INT NOT NULL,
  `fornecedor` INT NOT NULL,
  INDEX `fk_Eventos_has_Fornecedor_Fornecedor1_idx` (`fornecedor` ASC),
  INDEX `fk_Eventos_has_Fornecedor_Eventos1_idx` (`evento` ASC),
  PRIMARY KEY (`idProduto`),
  CONSTRAINT `fk_Eventos_has_Fornecedor_Eventos1`
    FOREIGN KEY (`evento`)
    REFERENCES `3762242_elevent`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`fornecedor`)
    REFERENCES `3762242_elevent`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3762242_elevent`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3762242_elevent`.`endereco` (
  `idEndereco` INT NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3762242_elevent`.`evento_has_checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3762242_elevent`.`evento_has_checklist` (
  `idEvento` INT NOT NULL,
  `idChecklist` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `idChecklist`),
  INDEX `fk_evento_has_checklist_checklist1_idx` (`idChecklist` ASC),
  INDEX `fk_evento_has_checklist_evento1_idx` (`idEvento` ASC),
  CONSTRAINT `fk_evento_has_checklist_evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `3762242_elevent`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_checklist_checklist1`
    FOREIGN KEY (`idChecklist`)
    REFERENCES `3762242_elevent`.`checklist` (`idChecklist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3762242_elevent`.`inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3762242_elevent`.`inscricao` (
  `idEvento` INT NOT NULL,
  `idParticipante` INT NOT NULL,
  `dataInscricao` DATE NOT NULL,
  `horaInscricao` TIME NOT NULL,
  PRIMARY KEY (`idEvento`, `idParticipante`),
  INDEX `fk_evento_has_participante_participante1_idx` (`idParticipante` ASC),
  INDEX `fk_evento_has_participante_evento1_idx` (`idEvento` ASC),
  CONSTRAINT `fk_evento_has_participante_evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `3762242_elevent`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_participante_participante1`
    FOREIGN KEY (`idParticipante`)
    REFERENCES `3762242_elevent`.`participante` (`idParticipante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
